# Numpy

In [1]:
import numpy as np

In [2]:
# Numpy is for array-> data of same type
# Type -> Single dimention and multi dimensional array

In [4]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr[1][1])

2
5


In [6]:
type(a)

numpy.ndarray

## Types of Array
#### Scalar = 0 Dimension , Rank=0
#### Vector = 1 Dimension , Rank=1
#### Matrix = 2 Dimension , Rank=2
#### Tensor = 3 or more Dimension , Rank=3

In [8]:
scalar=np.array(1)
scalar.ndim

0

In [9]:
vector=np.array([1,2,3])
vector.ndim

1

In [10]:
matrix=np.array([[1,2,3],[1,2,3],[1,2,3]])
matrix.ndim

2

In [11]:
tensor=np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
tensor.ndim

3

In [12]:
print (tensor) # as its an array you will not see comma's because its an array not list

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [13]:
# Creating array
l_array= np.array([1,2,3,4]) # from list
l_tuple= np.array((1,2,3,4)) # from tuple
print(l_array)
print(l_tuple)

[1 2 3 4]
[1 2 3 4]


#### Data type

In [18]:
int_array=np.array([1,2,3])
int_array.dtype

dtype('int32')

In [16]:
float_array=np.array([1.1,2,3])
float_array.dtype

dtype('float64')

In [17]:
string_array=np.array(["test","test1"])
string_array.dtype

dtype('<U5')

In [21]:
#forcing datatype
int_array_f=np.array([1,2,3], dtype=float)
int_array_f.dtype

dtype('float64')

In [22]:
int_array_f3=np.array([1,2,3], dtype=np.float32)
int_array_f3.dtype

dtype('float32')

In [36]:
#dtype= i1,i2,i3,i4,f2,f4,f8,u(unsign), c(complex),U(unicode),S(string),m,M(datetime)
int_array_type=np.array([1,2,3], dtype='m')
int_array_type.dtype


dtype('<m8')

In [40]:
#array of zeros
zero_arr1=np.zeros((1))
print(zero_arr1)
zero_arr2=np.zeros((2))
print(zero_arr2)
zero_arr2_2=np.zeros((2,2))
print(zero_arr2_2)
zero_arr3_3=np.zeros((3,3))
print(zero_arr3_3)

[0.]
[0. 0.]
[[0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
#array of ones
one_arr1=np.ones((1))
print(one_arr1)
one_arr2=np.ones((2))
print(one_arr2)
one_arr2_2=np.ones((2,2))
print(one_arr2_2)
one_arr3_3=np.ones((3,3))
print(one_arr3_3)

[1.]
[1. 1.]
[[1. 1.]
 [1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
#empty array - empty array is faster then zero
empty_arr1=np.empty((3))
print(empty_arr1)


[4.9e-324 9.9e-324 1.5e-323]


In [44]:
#arange: array of data with range n to m with step

arr_array=np.arange(2,8)
arr_array

array([2, 3, 4, 5, 6, 7])

In [45]:

arr_array1=np.arange(2,8,2)
arr_array1

array([2, 4, 6])

In [48]:
#linespace arrange of eqaulity divided number from n to m with x number
arr_linspace =np.linspace(2,8,num=5)
arr_linspace

array([2. , 3.5, 5. , 6.5, 8. ])

In [50]:
arr_linspace1 =np.linspace(11,20,num=10)
arr_linspace1

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [51]:
#reshape array
reshape_array=np.reshape(arr_linspace1,newshape=(2,5))
reshape_array

array([[11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [52]:
#nparray function
reshape_array.ndim


2

In [53]:
reshape_array.shape 

(2, 5)

In [54]:
reshape_array.size#number of elements

10

In [55]:
reshape_array.dtype

dtype('float64')

In [56]:
reshape_array.itemsize #dtype/8

8

In [61]:
#sort
a_unsort=np.array([5,2,3,7,9,8,0])
a_sort=np.sort(a_unsort)
print(a_sort)

[0 2 3 5 7 8 9]


In [63]:
#concatenate
a1=np.array([6,8,6,2,3,5])
a2=np.array([1,9,6,2,4,5])
a_con=np.concatenate((a1,a2))
a_con

array([6, 8, 6, 2, 3, 5, 1, 9, 6, 2, 4, 5])

In [66]:
a1_1=np.array([[6,8,6],[2,3,5]])
a2_2=np.array([[1,9,6],[2,4,5]])
a_con_1=np.concatenate((a1_1,a2_2), axis=0)
a_con_1

array([[6, 8, 6],
       [2, 3, 5],
       [1, 9, 6],
       [2, 4, 5]])

In [67]:
a_con_1=np.concatenate((a1_1,a2_2), axis=1)
a_con_1

array([[6, 8, 6, 1, 9, 6],
       [2, 3, 5, 2, 4, 5]])

#### Array Indexing and slicing

In [20]:
# Array Indexing and slicing
'''
1. If x = [4,6,17,8,9,3,15,12,7,13] convert x to ndarray and print:
a. value 17 and 7 separately using their positive index
b. value 12 and 3 using their negative index
c. the range  of values from 8 to 12 using positive indices
d. the range  of values from 4 to 15 using negative indices
e. the range  of values from 17 to the end using positive indices
f. the range  of values from 6 to the end using negative indices
g. the range  of value from 17 to 3 using a mix of negative and positive indices
h. the range  of values from 3 to 7 using a mix of negative and positive indices
i. all the values using only positive indices
j. all the values using only negative indices
k. all the values without using any index.
l. all the values from beginning to value 12
m. all the values from 6 to the end

'''
a= np.array([4,6,17,8,9,3,15,12,7,13])

print(a) 
print(a[2],a[8]) #a
print(a[-3],a[-5]) #b
print(a[3:8]) #c
print(a[-10:-3]) #d
print(a[-8:]) #e
print(a[-9:])#f
print(a[2:-4]) #g
print(a[5:-1]) #h
print(a[0:10]) #i
print(a[-10:]) #j
print(a[:]) #k
print(a[:-2]) #l
print(a[1:]) #l


[ 4  6 17  8  9  3 15 12  7 13]
17 7
12 3
[ 8  9  3 15 12]
[ 4  6 17  8  9  3 15]
[17  8  9  3 15 12  7 13]
[ 6 17  8  9  3 15 12  7 13]
[17  8  9  3]
[ 3 15 12  7]
[ 4  6 17  8  9  3 15 12  7 13]
[ 4  6 17  8  9  3 15 12  7 13]
[ 4  6 17  8  9  3 15 12  7 13]
[ 4  6 17  8  9  3 15 12]
[ 6 17  8  9  3 15 12  7 13]


In [33]:
# Array condition
'''
Create a two dimensional array for numbers between 1 and 25. Using the array, find the following:
1. all the even numbers
2. all numbers that are divisible by 4
3. all factors of 100
4. all the numbers less than or equal to 5, greater 20 or equal to 15
5. all odd numbers that are divisible by six
'''
a=np.arange(1,26)
print(a[(a%2==0)])
print(a[(a%4==0)])
print(a[(100%a==0)])
print(a[(a<=5) | (a>20) |(a==15)]) # or condition
print(a[(a%2==1) & (a%6==0)]) # and condition

[ 2  4  6  8 10 12 14 16 18 20 22 24]
[ 4  8 12 16 20 24]
[ 1  2  4  5 10 20 25]
[ 1  2  3  4  5 15 21 22 23 24 25]
[]


In [44]:
# 2D array
'''
a. Create a two dimensional array for numbers between 1 and 25.
Using the array, find the following:
1. all the numbers in the row 0
2. all the numbers in the column 2
3. numbers between 16 and 18
4. number 16, 17, 18, 21, 22 and 23
5. number 13
6. all the numbers in row 2 and 3
7. all the numbers in column 2 and 3
'''
a= np.arange(1,26).reshape(5,5)
print(a)
print(a[0])
print(a[:,2:3])
print(a[3,:3])
print(a[3:,:3])
print(a[2,2])
print(a[2:4])
print(a[:,2:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[[ 3]
 [ 8]
 [13]
 [18]
 [23]]
[16 17 18]
[[16 17 18]
 [21 22 23]]
13
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [47]:
#3D array
'''
Create a 3-D numpy array with numbers from 1 to 72.
Using the above array, print:
1. number 10
2. the first 2-D in the 3-D array
3. number 31 to 36
4. number 63 to 65
5. number 35
6. number 10, 34 and 66
7. column 3 in the third 2-D in the 3-D array
8. number 34 and 35
9. the first row in the last 2-D in the 3-D array
10. the last 2-D in the 3-D array
11. first row each in the second and third 2-D in the 3-D array
12. number 26 and 50
13. first two rows each from all the 2-D in the 3-D array
14. the entire last column of the 3-D array
15. the entire third column of the second and last 2-D in the 3-D
16. number less than 50 in the 3rd column of the second and last 2-D in the 3-D
17. numbers that are divisible by 5 in column 2 of second and third 2-D in the 3-D array
'''
a= np.arange(1,73).reshape(3,4,6)
print(a)


[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]
  [37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]
  [61 62 63 64 65 66]
  [67 68 69 70 71 72]]]


In [86]:
#print(a[0,1,3])#1
#print(a[0]) #2
#print(a[1,1])#3
#print(a[2,2,2:5])#4
#print(a[1,1,4])#5
#print(a[0][1][3], a[1][1][3],a[2][2][5])#6
#print(a[2,:,2:3])#7
#print(a[1,1,3:5])#8
#print(a[2,0])#9
#print(a[2])#10
#print(a[1:,0])#11
#print(a[1:,0,1:2])#12
#print(a[:,0:2])#13
#print(a[:,:,5:])#14
#print(a[1:,:,2:3])#15

print(a[1:,:,2:3][a[1:,:,2:3]<50])#16
print(a[1:,:,2:3][a[1:,:,2:3]%5==0])#17

[27 33 39 45]
[45]


In [90]:
#### array flattern & Ravel

b= np.arange(1,26).reshape(5,5)
b
print(b.flatten()) #shallow copy
print(b.ravel()) #deep copy
print(b.flatten().copy()) #deep copy


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [91]:
#Transpose
b= np.arange(1,26).reshape(5,5)
b.transpose()

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [94]:
#reverse
b= np.arange(1,26).reshape(5,5)
print(np.flip(b))
print(np.flip(b, axis=0)) #rows
print(np.flip(b, axis=1)) #column

[[25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


In [102]:
#unique array
d= np.concatenate((b,b), axis=1)
y= np.unique(d)
print(y)
z,ind= np.unique(d, return_index=True) #get index
print(z,ind)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25] [ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
 44]


In [109]:
#min, max , sum
b= np.arange(1,26).reshape(5,5)
print(b.min())
print(b.max())
print(b.sum())

#along axis
print(b.min(axis=0))
print(b.min(axis=1))
print(b.max(axis=0))
print(b.max(axis=1))
print(b.sum(axis=0))
print(b.sum(axis=1))


1
25
325
[1 2 3 4 5]
[ 1  6 11 16 21]
[21 22 23 24 25]
[ 5 10 15 20 25]
[55 60 65 70 75]
[ 15  40  65  90 115]


In [110]:
a=np.array([[1,2,3],[6,7,8]])
b=np.array([[4,5,9],[11,12,15]])

In [112]:
# Array stacking
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[ 1  2  3  4  5  9]
 [ 6  7  8 11 12 15]]
[[ 1  2  3]
 [ 6  7  8]
 [ 4  5  9]
 [11 12 15]]


In [125]:
#Array split
x=np.arange(1,49).reshape(2,24)
print(np.hsplit(x,6))# split into 6 equal array with column
print(np.vsplit(x,2)) # split into 2 equal array with rows

a,b,c=np.hsplit(x,(5,8))# split unequal array from 0-4 then 5 -7 and rest
print(a,b,c)

[array([[ 1,  2,  3,  4],
       [25, 26, 27, 28]]), array([[ 5,  6,  7,  8],
       [29, 30, 31, 32]]), array([[ 9, 10, 11, 12],
       [33, 34, 35, 36]]), array([[13, 14, 15, 16],
       [37, 38, 39, 40]]), array([[17, 18, 19, 20],
       [41, 42, 43, 44]]), array([[21, 22, 23, 24],
       [45, 46, 47, 48]])]
[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48]])]
[[ 1  2  3  4  5]
 [25 26 27 28 29]] [[ 6  7  8]
 [30 31 32]] [[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]]


In [126]:
#copy

b=x.copy()
c=x[1:3,1:].copy()

print(b)
print(c)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]]
[[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]]


In [127]:
#array operator
a=np.array( [1,2,3,4,5])
b=np.array([6,7,8,9,10])

print(a+b)
print(a-b)
print(2*a)
print(b**2)
print (a*b)
print(a%2)
print(b/a)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 2  4  6  8 10]
[ 36  49  64  81 100]
[ 6 14 24 36 50]
[1 0 1 0 1]
[6.         3.5        2.66666667 2.25       2.        ]


In [129]:
# delete
b= np.delete(a,3)
print (b)

x=[3,4]

c=np.setdiff1d(a,x)
print(c)

[1 2 3 5]
[1 2 5]


In [138]:
# insert
print(a)
b= np.append(a,44)  #at end
print (b)
b= np.append(a,[44,45,46]) #at end
print (b)

b= np.insert(a,2,66) #after element 2
print (b)
b= np.insert(a,1,[66,67,68]) #after element 1
print (b)

[1 2 3 4 5]
[ 1  2  3  4  5 44]
[ 1  2  3  4  5 44 45 46]
[ 1  2 66  3  4  5]
[ 1 66 67 68  2  3  4  5]


In [144]:
# New axis

a= np.arange(1,6)
a
b= a[np.newaxis,:] # add new dimention as row
c= a[:,np.newaxis] # add new dimention as column
d= a[np.newaxis,:,np.newaxis]
print(b)
print(b.ndim)
print(b.shape)
print(c)
print(c.ndim)
print(c.shape)
print(d)
print(d.ndim)
print(d.shape)

[[1 2 3 4 5]]
2
(1, 5)
[[1]
 [2]
 [3]
 [4]
 [5]]
2
(5, 1)
[[[1]
  [2]
  [3]
  [4]
  [5]]]
3
(1, 5, 1)


In [145]:
#Trigonomatry
#1 degree= pi/180 radian
import numpy as np
np.sin(90)
np.sin(90*np.pi/180)
np.cos(60)
np.cos(60*np.pi/180)
np.tan(70)
np.tan(60*np.pi/180)

1.7320508075688767

In [151]:
# searching in array
a= np.arange(1,11)
print (a)

print( np.where(a==6)) #index 5
print( np.where(a%2==0)) # index of 2,4,6,8,10

[ 1  2  3  4  5  6  7  8  9 10]
(array([5], dtype=int64),)
(array([1, 3, 5, 7, 9], dtype=int64),)


In [154]:
# Multiplication

a= np.arange(1,5).reshape(2,2)
b= np.arange(6,10).reshape(2,2)
print(np.multiply(a,5))
print(np.dot(a,b)) # matrix multiplication


[[ 5 10]
 [15 20]]
[[22 25]
 [50 57]]


In [156]:
# trace => sum of diagonal

a= np.arange(1,13).reshape(4,3)
print(a)
print(np.trace(a))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
15


In [157]:
#outer Product => each number by each number =>4*4=16
a= np.arange(1,5).reshape(2,2)
b= np.arange(6,10).reshape(2,2)
print(a)
print(b)
print(np.outer(a,b))


[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[ 6  7  8  9]
 [12 14 16 18]
 [18 21 24 27]
 [24 28 32 36]]


In [158]:
#inner product => each row by row =>Xrow1 *Yrow1, Xrow1 *Yrow2, Xrow2* Yrow1=> 4*4=>4
a= np.arange(1,5).reshape(2,2)
b= np.arange(6,10).reshape(2,2)
print(a)
print(b)
print(np.inner(a,b))

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[20 26]
 [46 60]]


In [159]:
#cross product Xrow1 *Yrow 1 , Xrow2* Yrow2 4*4=>2
a= np.arange(1,5).reshape(2,2)
b= np.arange(6,10).reshape(2,2)
print(a)
print(b)
print(np.cross(a,b))

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[-5 -5]


In [160]:
#kronecker product multiply each number of x with y 4*4 =16
#x1*y=4, x2*y=4 and so one 4+4+4+4
a= np.arange(1,5).reshape(2,2)
b= np.arange(6,10).reshape(2,2)
print(a)
print(b)
print(np.kron(a,b))

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[ 6  7 12 14]
 [ 8  9 16 18]
 [18 21 24 28]
 [24 27 32 36]]


In [161]:
#determinant same as matrix
a= np.arange(1,10).reshape(3,3)

print(a)

print(np.linalg.det(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16


In [163]:
#inverse same as matrix (transpose(cofactor)/determinant)
a= np.arange(1,10).reshape(3,3)
print(a)
print(np.linalg.inv(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [164]:
#Condition Number
#its a number if added to a function it effect the function
x= np.array([[2,3],[6,7]])
print(np.linalg.cond(x))

24.459115447074858


## Random

In [166]:
from numpy import random

In [176]:
#random integer
print (random.randint(20))# number between 1-20
print (random.rand(5))# 5 number between 0 to 1

print (random.randint(20,size=(5)))# number between 1-20 get 5 number
print (random.randint(20,size=(4,2)))# number between 1-20 get 4*2 array

#choice
a= np.array([4,5,9,20,1,2,11,15])
print (random.choice(a))# get number from a
print (random.choice(a,size=(5)))# get 5 number from a
print (random.choice(a,size=(4,2)))# get 4 by 2 number from a



5
[0.04251424 0.18701012 0.70244994 0.69992192 0.45363417]
[17  0  2 14 17]
[[ 9  1]
 [12  3]
 [ 7  9]
 [11 11]]
15
[ 9  1 20  4  1]
[[ 4  9]
 [ 5 11]
 [ 5  9]
 [ 2  4]]


In [183]:
# seed => it will choose same random number , result will be same every time
random.seed(0)
print (random.randint(20, size=(5)))# number between 1-20 ##[12 15  0  3  3]
random.seed(1)
print (random.randint(20, size=(5)))# number between 1-20 ##[ 5 11 12  8  9]
random.seed(2)
a= np.array([4,5,9,20,1,2,11,15])
print (random.choice(a,size=(5)))# [ 4 15  2  4 11]

[12 15  0  3  3]
[ 5 11 12  8  9]
[ 4 15  2  4 11]


In [187]:
# data distribution 
print (random.choice([3,4,6],p=[.2,.5,.3],size=(20))) # p is probability of 3,4,6 respectively
print (random.choice([3,4,6],p=[.2,.5,.3],size=(4,5)))

[4 6 6 6 4 4 4 4 6 4 6 6 4 6 4 6 4 6 4 4]
[[4 4 3 4 4]
 [6 6 4 6 6]
 [6 6 3 6 6]
 [6 4 4 4 4]]


In [3]:
# Data distribution => Distribution of data in the set

from numpy import random
a= random.choice([3,4,6], p=[0.7,0.1,0.2], size=20) # where is the percentage for distribution 3 will be highest as more probability in set of 20
a

array([6, 3, 3, 3, 3, 3, 6, 3, 3, 3, 3, 3, 4, 6, 3, 3, 4, 3, 6, 3])

In [7]:
a_m= random.choice([3,4,6], p=[0.2,0.6,0.2], size=(2,4)) # now 4 will be more
a_m

array([[4, 4, 6, 4],
       [4, 4, 4, 6]])